import 'dart:math' as math;

/// The Unit Converter tool's catalogue, as data rather than as closures.
///
/// This exists in its own file, free of any Flutter import, because three
/// things now read it: the converter page, the Swift copy that backs the
/// Shortcuts "Convert Unit" action (generated by
/// `tool/gen_swift_units.dart`, which imports this file), and the test that
/// checks the two have not drifted apart.
///
/// Every conversion here is affine — `base = value * factor + offset` — which
/// covers all nine categories, temperature included. That is the same shape
/// the hand-written functions in [units.dart] already had: `in2m` multiplies
/// by 0.0254 and `m2in` divides by it, so moving to a factor changes no
/// arithmetic. `test/converter_catalog_test.dart` pins that down against the
/// original functions, temperature included, where `(v - 32) * 5 / 9` and
/// `v * 5/9 - 160/9` agree to within rounding.
///
/// Note that [ConverterCategory.name] is deliberately English in every
/// locale, matching the chips the converter page has always drawn. The tool
/// titles that reach Shortcuts *are* localized — those come from the running
/// app (see `lib/util/shortcut_bridge.dart`) rather than from here.
class ConverterUnit {
  const ConverterUnit(this.label, this.factor, [this.offset = 0]);

  /// The suffix shown in the picker, e.g. `mm`, `lbf·ft`, `°F`.
  final String label;

  /// Multiplier onto the category's base unit.
  final double factor;

  /// Added after [factor], for the two temperature scales that do not share
  /// zero with Celsius. Zero everywhere else.
  final double offset;

  double toBase(double value) => value * factor + offset;

  double fromBase(double base) => (base - offset) / factor;
}

class ConverterCategory {
  const ConverterCategory({
    required this.id,
    required this.name,
    required this.baseLabel,
    required this.units,
  });

  /// Stable identifier. Written into the shared App Group store and used as
  /// the Shortcuts parameter value, so it must not change once shipped even
  /// if [name] is reworded.
  final String id;

  /// English display name, as drawn on the converter page's chips.
  final String name;

  /// The unit [ConverterUnit.factor] and [ConverterUnit.offset] are relative
  /// to. Never shown; it is here so the generated Swift can document itself.
  final String baseLabel;

  final List<ConverterUnit> units;

  ConverterUnit? unitByLabel(String label) {
    for (final unit in units) {
      if (unit.label == label) return unit;
    }
    return null;
  }
}

/// Degrees Fahrenheit onto Celsius: `C = (F - 32) · 5/9`, rearranged into
/// `F · 5/9 + (-160/9)`.
const double _fahrenheitFactor = 5 / 9;
const double _fahrenheitOffset = -160 / 9;

const List<ConverterCategory> converterCategories = <ConverterCategory>[
  ConverterCategory(
    id: 'length',
    name: 'Length',
    baseLabel: 'm',
    units: [
      ConverterUnit('mm', 0.001),
      ConverterUnit('cm', 0.01),
      ConverterUnit('m', 1),
      ConverterUnit('km', 1000),
      ConverterUnit('in', 0.0254),
      ConverterUnit('ft', 0.3048),
      ConverterUnit('yd', 0.9144),
      ConverterUnit('mi', 1609.344),
    ],
  ),
  ConverterCategory(
    id: 'force',
    name: 'Force',
    baseLabel: 'N',
    units: [
      ConverterUnit('N', 1),
      ConverterUnit('kN', 1e3),
      ConverterUnit('MN', 1e6),
      ConverterUnit('lbf', 4.44822),
      ConverterUnit('kip', 4448.22),
    ],
  ),
  ConverterCategory(
    id: 'pressure',
    name: 'Stress / Pressure',
    baseLabel: 'Pa',
    units: [
      ConverterUnit('Pa', 1),
      ConverterUnit('kPa', 1e3),
      ConverterUnit('MPa', 1e6),
      ConverterUnit('GPa', 1e9),
      ConverterUnit('psi', 6894.76),
      ConverterUnit('ksi', 6.89476e6),
      ConverterUnit('atm', 101325),
      ConverterUnit('bar', 1e5),
    ],
  ),
  ConverterCategory(
    id: 'mass',
    name: 'Mass',
    baseLabel: 'kg',
    units: [
      ConverterUnit('g', 0.001),
      ConverterUnit('kg', 1),
      ConverterUnit('tonne', 1000),
      ConverterUnit('oz', 0.0283495),
      ConverterUnit('lb', 0.453592),
      ConverterUnit('slug', 14.5939),
    ],
  ),
  ConverterCategory(
    id: 'temperature',
    name: 'Temperature',
    baseLabel: '°C',
    units: [
      ConverterUnit('°C', 1),
      ConverterUnit('°F', _fahrenheitFactor, _fahrenheitOffset),
      ConverterUnit('K', 1, -273.15),
    ],
  ),
  ConverterCategory(
    id: 'torque',
    name: 'Torque',
    baseLabel: 'N·m',
    units: [
      ConverterUnit('N·m', 1),
      ConverterUnit('kN·m', 1000),
      ConverterUnit('lbf·ft', 1.35582),
      ConverterUnit('lbf·in', 0.112985),
    ],
  ),
  ConverterCategory(
    id: 'power',
    name: 'Power',
    baseLabel: 'W',
    units: [
      ConverterUnit('W', 1),
      ConverterUnit('kW', 1000),
      ConverterUnit('MW', 1e6),
      ConverterUnit('hp', 745.7),
    ],
  ),
  ConverterCategory(
    id: 'angularVelocity',
    name: 'Angular Velocity',
    baseLabel: 'rad/s',
    units: [
      ConverterUnit('rad/s', 1),
      ConverterUnit('rpm', math.pi / 30),
      ConverterUnit('deg/s', math.pi / 180),
    ],
  ),
  ConverterCategory(
    id: 'angle',
    name: 'Angle',
    baseLabel: 'rad',
    units: [
      ConverterUnit('rad', 1),
      ConverterUnit('deg', math.pi / 180),
    ],
  ),
];

ConverterCategory? converterCategoryById(String id) {
  for (final category in converterCategories) {
    if (category.id == id) return category;
  }
  return null;
}

/// Converts [value] from [from] to [to] within one category, via the base
/// unit. Both units must belong to the same category; nothing here checks
/// that, because the only callers pick both from the same [ConverterCategory].
double convertUnit(double value, ConverterUnit from, ConverterUnit to) =>
    to.fromBase(from.toBase(value));

/// How the converter writes a result: plain decimal with trailing zeros
/// stripped, falling back to exponential once the value is too large or too
/// small to read that way.
///
/// This is the converter tool's own format and deliberately not
/// `NumberPrecisionHelper.formatValue` — a conversion is exact, so it shows
/// everything it has rather than the significant figures a calculated result
/// is rounded to. `METoolkitShared/UnitConversion.swift` carries a Swift
/// translation of this function so the Shortcuts action prints the same
/// string as the app; `test/converter_catalog_test.dart` checks a table of
/// values against it.
String formatConverterValue(double v) {
  if (v == 0) return '0';
  final abs = v.abs();
  if (abs >= 1e6 || abs < 0.001) {
    // Strip the trailing zeros of the mantissa, and then the orphaned decimal
    // point they leave behind. Without that second step a round number
    // printed as "1.000000e+9" came out as "1.e+9" — 1 GPa in Pa, or a
    // millimetre in kilometres, both showed that stray point.
    return v
        .toStringAsExponential(6)
        .replaceAll(RegExp(r'0+e'), 'e')
        .replaceAll('.e', 'e');
  }
  final s = v.toStringAsFixed(8);
  return s.contains('.')
      ? s.replaceAll(RegExp(r'0+$'), '').replaceAll(RegExp(r'\.$'), '')
      : s;
}
